### ISSUE TITLE
Disabling controls during ajax data loading

### ISSUE THREAD

**Issue by ndarao** [Upande/MaMaSe#11]
Attempt to change options in any of the dropdown lists that require fresh load of data  from the API produces errors or confusion in the displayed data. We should attempt to disable them during data load, and offer an indicator that data is being loaded

**Comment by mekoki** [comment]
Have worked on it. The whole page is disabled when data is being pulled from thinkspeak.  May still need modification to work properly with monthly and daily aggregated data. currently working fine with raw data as of commit 444c4952770ce90d57b530ba10512dd5eb426e7f

**Comment by itsMagondu** [comment]
@ndarao I believe this is already working right? If so, could you please close the issue?
