### ISSUE TITLE
Developing the Rainfall Temperature interface 

### ISSUE THREAD

**Issue by mekoki** [Upande/MaMaSe#14]
This interface should display Temperature and Rainfall only

**Comment by ndarao** [comment]
currently working on this... Bring up several more issues
-modify the existing interface to generate and display html controls dynamically
-code the so generated control to respond to Onchange event

**Comment by itsMagondu** [comment]
Related to #58

**Comment by itsMagondu** [comment]
Seems this view only needs aggregated monthly data. See below.

![image](https://cloud.githubusercontent.com/assets/1202275/18552720/5bbb46ba-7b66-11e6-960b-ae2219548f78.png)

**Comment by itsMagondu** [comment]
And maybe daily. So just aggregated values.
