### ISSUE TITLE
Code the aggregation dropdown

### ISSUE THREAD

**Issue by mekoki** [Upande/MaMaSe#16]
The Aggregation button determines which aggregation function is used to plot the monthly and daily data. Should be inactive when the time interval selection=raw-data

**Comment by mekoki** [comment]
Added aggregation_variable to hold the selected aggregation variable
Added an Aggregation function to respond on change
Should load appropriate data from myarry
should call drawGraph fxn after that

**Comment by itsMagondu** [comment]
I believe this has been done
