### ISSUE TITLE
Aesthetical aspect of the User Interface (UI)

### ISSUE THREAD

**Issue by mekoki** [Upande/MaMaSe#18]
The whole page need to be modified so that the controls are laid on the page properly. Currently the controls are not well lined up in the page.

**Comment by itsMagondu** [comment]
@mekoki Having a look at http://mamase.org/mamase/chart, do you think they are well lined now? If so, please close the issue

**Comment by itsMagondu** [comment]
I assume this is fixed. If not please reopen @mekoki
