### ISSUE TITLE
Develop UI for pulling and visualizing data from multiple stations on the same graph 

### ISSUE THREAD

**Issue by mekoki** [Upande/MaMaSe#20]
The current UI enables us to pull data for one station at a time. In order to enable comparison of different weather variables in the weather stations, there is need to come up with a logic on how data can be pulled and processed on the UI.

**Comment by itsMagondu** [comment]
I believe this is enabled when pulling aggregated data for the table. However the UI seems to be outside of the scope of this project. Closing the issue for now
